Fix compilation with clang++
Remove unused member:

  In file included from .../src/clustering.cpp:23:
  .../src/clustering.hpp:259:17: error: private field 'axisIndex_' is not used [-Werror,-Wunused-private-field]
      mutable int axisIndex_;
                  ^
  .../src/clustering.hpp:260:17: error: private field 'spatialDimension_' is not used [-Werror,-Wunused-private-field]
      mutable int spatialDimension_;
                  ^

Define Timeline::~Task when HMAT_TIMELINE is OFF, otherwise
clang++ reports an error:

  .../src/scalar_array.cpp:299:18: error: unused variable 't' [-Werror,-Wunused-variable]
    Timeline::Task t(Timeline::BLASGEMM, &rows, &cols, &k, &tA, &tB);
                   ^